name: Year of 300
favicon: null
layout_spectrum: 0.22156411549076438
typography_spectrum: 0.7175947912037373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.21464424207806587
  lightness: 0.9786116785835475
  saturation: 0.3464535663370043
  rhythmicContrast: 0.7772632730193436
purpose: []
